var mqtt = require('./lib/mqtt')
  , apns = require('./lib/apns');

// TODO: Flow control

// TODO: Redirector, use DNS#53 port to help with firewall
// ...
// UDP redirector need use session validation
// device 需要生成一个 random, 服务端回应 ~random...
// device 需验证
// ...
// 直接使用 DNS 技术... OK 了...
// 使用 SRV 记录, 使用脚本生成 映射配置文件...
